CREATE TABLE CartsProducts(
 CartsProductsID UNIQUEIDENTIFIER PRIMARY KEY, 
 FK_ProductsID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
 FK_CartID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Carts(CartsID))

