CREATE TABLE Carts(
 CartsID UNIQUEIDENTIFIER PRIMARY KEY, 
 CartsTotalPrice smallmoney NOT NULL,
 CartItems Integer NOT NULL,
 FK_UserID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserID))

