CREATE TABLE Profiles(
 ProfileID UNIQUEIDENTIFIER PRIMARY KEY, 
 ProfileName VARCHAR(100) NOT NULL,
 ProfileAddress VARCHAR(500) NULL,
 ProfilePhone VARCHAR(70) NULL,
 ProfileEmail VARCHAR(100) NOT NULL,
 ProductImage VARBINARY(MAX),
 Fk_UserID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(UserID))