DROP TABLE IF EXISTS OrdersProducts;
DROP TABLE IF EXISTS CartsProducts;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Carts;
DROP TABLE IF EXISTS Profiles;

CREATE TABLE Profiles(
	profileID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	profileName NVARCHAR(100),
	profileAddress NVARCHAR(100),
	profilePhone NVARCHAR(100),
	profileEmail NVARCHAR(100),
	profilePicture NVARCHAR(200),
	fk_userID NVARCHAR(100) NOT NULL,
	dateCreated DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dateModified DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Carts(
	cartID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	cartTotal SMALLMONEY,
	cartItems INT,
	fk_userID NVARCHAR(100) NOT NULL
);

CREATE TABLE Products(
	productID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	productName NVARCHAR(500) UNIQUE,
	productImage VARBINARY(MAX),
	productPrice SMALLMONEY,
	productDetails NVARCHAR(MAX),
	stockDate DATETIME2,
	stock INT,
	dateCreated DATETIME2 DEFAULT CURRENT_TIMESTAMP,
	dateModified DATETIME2 DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Orders(
	orderID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	orderTotal SMALLMONEY,
	dateOrdered DATETIME2 DEFAULT CURRENT_TIMESTAMP,
	dateDelivered DATETIME2,
	cancelled BIT DEFAULT 0,
	refunded BIT DEFAULT 0,
	fk_userID NVARCHAR(100) NOT NULL
);

CREATE TABLE CartsProducts(
	cartProductID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	fk_productID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Products(productID),
	fk_cartID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Carts(cartID)	
);

CREATE TABLE OrdersProducts(
	orderProductID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	fk_productID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Products(productID),
	fk_orderID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Orders(orderID)
);